import fs from 'fs';
import path from 'path';

export default function Page() {
  const filePath = path.join(process.cwd(), 'app', 'curved-glass-doors-modern-elegance-for-stylish-entrances', 'content.html');
  const html = fs.readFileSync(filePath, 'utf-8');
  return (
    <>
      <div className="wp-singular post-template-default single single-post postid-10157 single-format-standard wp-theme-Avada edd-js-none fusion-image-hovers fusion-pagination-sizing fusion-button_type-flat fusion-button_span-yes fusion-button_gradient-linear avada-image-rollover-circle-no avada-image-rollover-yes avada-image-rollover-direction-fade fusion-body ltr no-tablet-sticky-header no-mobile-sticky-header no-mobile-slidingbar fusion-disable-outline fusion-sub-menu-fade mobile-logo-pos-left layout-wide-mode avada-has-boxed-modal-shadow-none layout-scroll-offset-full avada-has-zero-margin-offset-top fusion-top-header menu-text-align-center mobile-menu-design-modern fusion-show-pagination-text fusion-header-layout-v6 avada-responsive avada-footer-fx-none avada-menu-highlight-style-bar fusion-search-form-classic fusion-main-menu-search-dropdown fusion-avatar-square avada-sticky-shrinkage avada-blog-layout-large avada-blog-archive-layout-large avada-header-shadow-no avada-menu-icon-position-left avada-has-mainmenu-dropdown-divider avada-has-header-100-width avada-has-mobile-menu-search avada-has-main-nav-search-icon avada-has-100-footer avada-has-titlebar-hide avada-header-border-color-full-transparent avada-social-full-transparent avada-has-pagination-padding avada-flyout-menu-direction-fade avada-ec-views-v1 awb-link-decoration" suppressHydrationWarning dangerouslySetInnerHTML={{ __html: html }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({"@context":"https://schema.org","@type":"BlogPosting","mainEntityOfPage":{"@type":"WebPage","@id":"https://secure-house-next-js.vercel.app/curved-glass-doors-modern-elegance-for-stylish-entrances"},"headline":"Curved Glass Doors | Elegant & Modern Architectural Designs","description":"Enhance your space with sleek curved glass doors. Perfect for modern homes, they offer panoramic views and seamless integration with your architecture.","image":"https://secure-house.co.uk/wp-content/uploads/al_opt_content/IMAGE/secure-house.co.uk/wp-content/uploads/2024/11/Group-84-1-200x83.png.bv.webp?bv_host=secure-house.co.uk","author":{"@type":"Organization","name":""},"publisher":{"@type":"Organization","name":"Secure House","logo":{"@type":"ImageObject","url":"https://secure-house.co.uk/wp-content/uploads/al_opt_content/IMAGE/secure-house.co.uk/wp-content/uploads/2024/11/Group-84-1-200x83.png.bv.webp?bv_host=secure-house.co.uk"}},"datePublished":"2025-10-14","dateModified":"2025-10-15"}) }} />
    
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"How much do curved glass doors cost in the UK?","acceptedAnswer":{"@type":"Answer","text":"Curved glass doors are a premium, made-to-measure product and pricing depends on size, radius, glazing specification and security features required. At Secure House, we provide a free, no-obligation quote tailored to your exact requirements. Contact us for a personalised consultation."}},{"@type":"Question","name":"Are curved glass doors secure?","acceptedAnswer":{"@type":"Answer","text":"Yes. All our curved glass doors are built with reinforced steel frames, 12-point multi-point locking and toughened safety glass as standard. Our doors are certified to EN 1627:2011 and PAS 24 \u2014 the same security standards across our full door range."}},{"@type":"Question","name":"Can curved glass doors be used as front doors?","acceptedAnswer":{"@type":"Answer","text":"Absolutely. A curved glass front door makes a stunning and highly secure entrance for residential and commercial properties alike. Each door is manufactured to your specific opening dimensions and radius."}},{"@type":"Question","name":"How long does it take to manufacture and install a curved glass door?","acceptedAnswer":{"@type":"Answer","text":"Lead times vary depending on specification and complexity. We will confirm a clear, agreed timeline during your consultation before any work begins."}},{"@type":"Question","name":"Do curved glass doors offer good insulation?","acceptedAnswer":{"@type":"Answer","text":"Yes. Our doors feature thermally broken frames and double glazing as standard, with triple-glazed options available \u2014 delivering excellent thermal and acoustic performance alongside their striking appearance."}},{"@type":"Question","name":"Can you fit a curved glass door to an existing opening?","acceptedAnswer":{"@type":"Answer","text":"Yes. Our team carries out a full site survey before manufacture to ensure your door is built to the precise dimensions of your existing opening for a perfect, weather-tight fit."}}]}) }} />
    </>
  );
}
