import fs from 'fs';
import path from 'path';

export default function Page() {
  const filePath = path.join(process.cwd(), 'app', 'arched-doors', 'content.html');
  const html = fs.readFileSync(filePath, 'utf-8');
  return (
    <>
      <div className="wp-singular post-template-default single single-post postid-9650 single-format-standard wp-theme-Avada edd-js-none fusion-image-hovers fusion-pagination-sizing fusion-button_type-flat fusion-button_span-yes fusion-button_gradient-linear avada-image-rollover-circle-no avada-image-rollover-yes avada-image-rollover-direction-fade fusion-body ltr no-tablet-sticky-header no-mobile-sticky-header no-mobile-slidingbar fusion-disable-outline fusion-sub-menu-fade mobile-logo-pos-left layout-wide-mode avada-has-boxed-modal-shadow-none layout-scroll-offset-full avada-has-zero-margin-offset-top fusion-top-header menu-text-align-center mobile-menu-design-modern fusion-show-pagination-text fusion-header-layout-v6 avada-responsive avada-footer-fx-none avada-menu-highlight-style-bar fusion-search-form-classic fusion-main-menu-search-dropdown fusion-avatar-square avada-sticky-shrinkage avada-blog-layout-large avada-blog-archive-layout-large avada-header-shadow-no avada-menu-icon-position-left avada-has-mainmenu-dropdown-divider avada-has-header-100-width avada-has-mobile-menu-search avada-has-main-nav-search-icon avada-has-100-footer avada-has-titlebar-hide avada-header-border-color-full-transparent avada-social-full-transparent avada-has-pagination-padding avada-flyout-menu-direction-fade avada-ec-views-v1 awb-link-decoration" suppressHydrationWarning dangerouslySetInnerHTML={{ __html: html }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({"@context":"https://schema.org","@type":"BlogPosting","mainEntityOfPage":{"@type":"WebPage","@id":"https://secure-house-next-js.vercel.app/arched-doors"},"headline":"Elegant Arched Doors | Premium Custom Arched Door Designs","description":"Explore elegant arched doors. Our bespoke arched door designs combine beauty and strength, perfect for enhancing homes with timeless style and charm.","image":"https://secure-house.co.uk/wp-content/uploads/al_opt_content/IMAGE/secure-house.co.uk/wp-content/uploads/2024/11/Group-84-1-200x83.png.bv.webp?bv_host=secure-house.co.uk","author":{"@type":"Organization","name":""},"publisher":{"@type":"Organization","name":"Secure House","logo":{"@type":"ImageObject","url":"https://secure-house.co.uk/wp-content/uploads/al_opt_content/IMAGE/secure-house.co.uk/wp-content/uploads/2024/11/Group-84-1-200x83.png.bv.webp?bv_host=secure-house.co.uk"}},"datePublished":"2025-10-14","dateModified":"2025-10-15"}) }} />
    
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What is the difference between an arch door and a standard front door?","acceptedAnswer":{"@type":"Answer","text":"An arch door features a curved or rounded top profile \u2014 semicircular, segmental or gothic \u2014 rather than the flat header of a standard rectangular door. This gives it a distinctive, architecturally rich appearance suited to both period and contemporary properties."}},{"@type":"Question","name":"Can you fit an arch door into an existing rectangular opening?","acceptedAnswer":{"@type":"Answer","text":"Yes. In most cases, an arched door frame can be installed into an existing rectangular opening, with the arched head formed within the new frame. Our team will assess your existing opening during a free site visit and advise on the best approach."}},{"@type":"Question","name":"Are arch doors secure?","acceptedAnswer":{"@type":"Answer","text":"Yes. Every arch door we build at Secure House includes a reinforced steel frame, 12-point multi-point locking, anti-drill manganese plating and toughened glass. All doors meet EN 1627:2011 and PAS 24 security standards."}},{"@type":"Question","name":"Do arch doors work on modern homes?","acceptedAnswer":{"@type":"Answer","text":"Absolutely. While arch doors have a strong heritage association, they are increasingly chosen for contemporary properties where architects and homeowners want to add sculptural warmth and character. We produce arch doors across all profiles to suit any architectural style."}},{"@type":"Question","name":"How long does it take to build and install an arch door?","acceptedAnswer":{"@type":"Answer","text":"Lead times depend on the specification and profile complexity. We will agree a clear, confirmed production and installation timeline with you before any work begins."}},{"@type":"Question","name":"Can you fit a curved glass door to an existing opening?","acceptedAnswer":{"@type":"Answer","text":"Yes. Our team carries out a full site survey before manufacture to ensure your door is built to the precise dimensions of your existing opening for a perfect, weather-tight fit."}}]}) }} />
    </>
  );
}
